// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVkfnU1TKQ5-CjzWJzEAqndmYTKVFxHzs',
    appId: '1:378810693609:web:ad3371b150cc0749c4fd78',
    messagingSenderId: '378810693609',
    projectId: 'task-project-230459',
    authDomain: 'task-project-230459.firebaseapp.com',
    storageBucket: 'task-project-230459.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP_A63_F9Tkl56DJOAYbNLpoK4JbedOGw',
    appId: '1:378810693609:android:e5c2cc93c8209692c4fd78',
    messagingSenderId: '378810693609',
    projectId: 'task-project-230459',
    storageBucket: 'task-project-230459.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhQv84TkLaLPM6agjKd9WYZEY1JxhEO1Q',
    appId: '1:378810693609:ios:0fb0a8bcbeeaec50c4fd78',
    messagingSenderId: '378810693609',
    projectId: 'task-project-230459',
    storageBucket: 'task-project-230459.appspot.com',
    iosBundleId: 'com.example.outtaskapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhQv84TkLaLPM6agjKd9WYZEY1JxhEO1Q',
    appId: '1:378810693609:ios:d3ebd9e7c1d8efeac4fd78',
    messagingSenderId: '378810693609',
    projectId: 'task-project-230459',
    storageBucket: 'task-project-230459.appspot.com',
    iosBundleId: 'com.example.outtaskapp.RunnerTests',
  );
}
